services:
  - type: web
    name: factrust
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    plan: free
    runtime: python
    pythonVersion: 3.10
