services:
  - type: web
    name: factrust-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    runtime: python
    pythonVersion: 3.10
